### ISSUE TITLE
Guidance to re-train explorer and smoother model

### ISSUE THREAD

**Issue by wenjinzhang** [rainorangelemon/gnn-motion-planning#3]
Hi

Thank you very much for sharing your work. Would you please provide guidance to re-train the explorer and smoother models? I am also interested in how to generate the training dataset. Thank you in advance.

Best regards,
Wenjin

**Comment by rainorangelemon** [comment]
Hello Wenjin,

Thanks for asking! 

Please take a look at `train_explorer.py` and `train_smoother.py` for the training procedure. The code currently is a bit messy, so I do want to refactor them in the future. Please stay tuned.

To generate the dataset, I first generate a bunch of cases where the obstacles and the configurations of the robot are randomly sampled. Then, I use the BIT* planner with a much longer timeout (e.g., 10 mins), to find the test cases which contain feasible solutions. These cases where BIT* with longer timeout succeeds are saved as the dataset (including the training and test dataset). I will try my best to find the codes where I generate these datasets, but I cannot guarantee since  I put these codes separately somewhere on a computer that I haven't used for nearly 1.5 years... But I hope you can get a sense about how I generate the dataset based on the description above.

Let me know if there are any other questions! I'd love to help.

**Comment by wenjinzhang** [comment]
Hi,

Thank you very much for the explanation. 
After checking ``` train_explorer.py``` and ```train_smoother.py```, I got it. 
I also got how to generate the dataset. This makes sense to me. I understand it is hard to find the old code. Hopefully, you can find it and post it on your repo. We appreciate your work.

Best regards,
Wenjin
